--EXPLORATORY DATA ANALYSIS

-- To check userId
SELECT USERID
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;

-- To check different channel contents
SELECT DISTINCT(channel2)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;


-- To check different channel contents
SELECT DISTINCT(RECORDDATE2)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;


--To extract year from recorddate2 
SELECT EXTRACT(YEAR from (TO_DATE(RECORDDATE2,'YYYY/MM/DD MI:SS'))) AS YEAR_WATCHED
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;

-- To get monthname from recorddate2 
SELECT MONTHNAME(TO_DATE(RECORDDATE2,'YYYY/MM/DD MI:SS')) AS MONTH_WATCHED
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;

-- To get dayname from recorddate2 
SELECT DAYNAME(TO_DATE(RECORDDATE2,'YYYY/MM/DD MI:SS')) AS DAY_WATCHED
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;


-- To get time from recordate
SELECT TIME(TO_TIMESTAMP(RECORDDATE2,'YYYY/MM/DD HH24:MI')) AS TIME_WATCHED
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;

-- To get max time from recordate
SELECT MAX(TIME(TO_TIMESTAMP(RECORDDATE2,'YYYY/MM/DD HH24:MI'))) AS TIME_WATCHED
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;

-- To get min time from recordate
SELECT MIN(TIME(TO_TIMESTAMP(RECORDDATE2,'YYYY/MM/DD HH24:MI'))) AS TIME_WATCHED
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;


-- To check how long was a content watched
SELECT DISTINCT(DURATION2)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;

-- To check how longest duration a content was  watched
SELECT MAX(DURATION2)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;

-- To check how shortest duration a content was  watched
SELECT MIN(DURATION2)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1;

-- To check names of users
SELECT DISTINCT(NAME)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2
WHERE NAME <> 'None';

-- To check surnames of users
SELECT DISTINCT(SURNAME)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2
WHERE SURNAME <> 'None';

-- To check emails of users
SELECT DISTINCT(EMAIL)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2;

-- To check RACE of users
SELECT DISTINCT(RACE)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2
WHERE RACE IS NOT NULL AND RACE <> 'None';

-- To check AGE of users
SELECT DISTINCT(AGE)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2;

-- To check highest age of users
SELECT MAX(AGE)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2;

-- To check lowest age of users
SELECT MIN(AGE)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2;

-- To check gender of users
SELECT DISTINCT(GENDER)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2
WHERE GENDER <> 'None' AND GENDER IS NOT NULL;

-- To check Province of users
SELECT DISTINCT(PROVINCE)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2
WHERE PROVINCE <> 'None' AND PROVINCE IS NOT NULL;

-- To check users' Social media handle
SELECT DISTINCT(SOCIAL_MEDIA_HANDLE)
FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2;
--------------------------------------------------------------------------------------------------------------------------------------------------------------
--CODE

SELECT A.USERID,
    channel2,
    CASE
        WHEN channel2 IN ('Trace TV', 'Channel O', 'Vuzu', 'E! Entertainment') THEN 'Music/Entertainment'
        WHEN channel2 IN ('kykNET', 'MK', 'Africa Magic') THEN 'Local/Regional Content'
        WHEN channel2 IN ('Wimbledon', 'SuperSport Live Events', 'Supersport Live Events', 
                          'ICC Cricket World Cup 2011', 'Live on SuperSport', 'SuperSport Blitz') THEN 'Sports'
        WHEN channel2 = 'M-Net' THEN 'Movies/Premium'
        WHEN channel2 IN ('Cartoon Network', 'Boomerang') THEN 'Kids/Animation'
        WHEN channel2 IN ('DStv Events 1') THEN 'Special Events'
        WHEN channel2 IN ('Break in transmission', 'SawSee', 'Sawsee') THEN 'Miscellaneous / Unclassified Content'
        ELSE 'Other'
    END AS channel_category,
    

DATEADD(HOUR,2,TO_TIMESTAMP(RECORDDATE2,'YYYY/MM/DD HH24:MI')) AS RECORDDATE,
    EXTRACT(YEAR from (TO_DATE(RECORDDATE2,'YYYY/MM/DD HH24:MI'))) AS YEAR_WATCHED,
    MONTHNAME(TO_DATE(RECORDDATE2,'YYYY/MM/DD HH24:MI')) AS MONTH_WATCHED,
    EXTRACT(DAY from (TO_DATE(RECORDDATE2,'YYYY/MM/DD HH24:MI'))) AS DAY_WATCHED,
    DAYNAME(TO_DATE(RECORDDATE2,'YYYY/MM/DD HH24:MI')) AS DAYNAME_WATCHED,
    TIME(DATEADD(HOUR,2,TO_TIMESTAMP(RECORDDATE2,'YYYY/MM/DD HH24:MI'))) AS TIME_WATCHED,
    EXTRACT(HOUR FROM DATEADD(HOUR,2,TO_TIMESTAMP(RECORDDATE2,'YYYY/MM/DD HH24:MI'))) AS HOUR_WATCHED,

    COUNT(*) AS Total_users,

    CASE
   WHEN TIME_WATCHED BETWEEN '00:00:00' AND '05:59:59' THEN 'Late Night'
   WHEN TIME_WATCHED  BETWEEN '06:00:00' AND '11:59:59' THEN 'Morning'
   WHEN TIME_WATCHED  BETWEEN '12:00:00' AND '17:59:59' THEN 'Afternoon'
   WHEN TIME_WATCHED  BETWEEN '18:00:00' AND '23:59:59' THEN 'Evening'
    ELSE 'Unknown'
  END AS Time_of_day,

  CASE
  WHEN DAYNAME_WATCHED NOT IN('Sat', 'Sun') THEN 'Weekday_watches'
  ELSE 'Weekend_watches'
  END AS WEEK_WATCHES,
    

    DURATION2 AS viewing_duration,
    CASE
        WHEN duration2 <= '01:00:00' THEN 'Short Duration'
        WHEN duration2 BETWEEN '01:00:00' AND '04:00:00' THEN 'Medium Duration '
        WHEN duration2 BETWEEN '04:00:00' AND  '11:29:28' THEN 'Long Duration'
        ELSE 'Other / Unusual duration'
    END AS duration_category_description,

    
    NAME,
    SURNAME,
    EMAIL,
    GENDER,
    RACE,
AGE,
CASE
        WHEN age BETWEEN 0 AND 12 THEN 'Child (0-12)'
        WHEN age BETWEEN 13 AND 17 THEN 'Teen (13-17)'
        WHEN age BETWEEN 18 AND 24 THEN 'Young Adult (18-24)'
        WHEN age BETWEEN 25 AND 34 THEN 'Adult (25-34)'
        WHEN age BETWEEN 35 AND 44 THEN 'Mid-Age Adult (35-44)'
        WHEN age BETWEEN 45 AND 54 THEN 'Mature Adult (45-54)'
        WHEN age BETWEEN 55 AND 64 THEN 'Senior (55-64)'
        WHEN age BETWEEN 65 AND 114 THEN 'Elderly (65+)'
        ELSE 'Unknown / Invalid Age'
    END AS age_group,

    PROVINCE,
    SOCIAL_MEDIA_HANDLE

    FROM CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE1 AS A
    FULL OUTER JOIN CASE_STUDY3.BRIGHTTV_VIEWERSHIP.TABLE2 AS B
    ON A.USERID = B.USERID 
    
    WHERE NAME <> 'None' AND SURNAME <> 'None'AND RACE IS NOT NULL AND RACE <> 'None' AND GENDER <> 'None' AND GENDER IS NOT NULL AND PROVINCE <> 'None' AND PROVINCE IS NOT NULL
    GROUP BY ALL;
